<buildinfo>
	<type>exe</type>
	<input>MainWindow.cs</input>
	<package>gtk-sharp-2.0</package>
	<package>glade-sharp-2.0</package>
	<reference>Mono.Posix</reference>	
	<output>bless.exe</output>
	<extra>-nowarn:0169</extra>
</buildinfo>
