<buildinfo>
	<type>library</type>
	<input>*.cs</input>
	<ignore>StatisticsPlugin.cs</ignore>
	<package>gtk-sharp-2.0</package>
	<package>glade-sharp-2.0</package>
	<reference>Mono.Cairo.dll</reference>
	<reference>Mono.Posix</reference>
	<output>Bless.Gui.Plugins.dll</output>
	<extra>-nowarn:0169</extra>
</buildinfo>
