<buildinfo>
	<type>library</type>
	<input>*.cs</input>
	<ignore>Area.cs</ignore>
	<ignore>AreaGroup.cs</ignore>
	<ignore>Highlight.cs</ignore>
	<package>gtk-sharp-2.0</package>
	<output>Bless.Gui.Areas.Plugins.dll</output>
</buildinfo>
